/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:    sensirion-driver-generator 0.21.0
 * Product:      sfc6xxx
 * Version:      1.1
 */
/*
 * Copyright (c) 2023, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sfc6xxx_uart.h"
#include "sensirion_common.h"
#include "sensirion_shdlc.h"
#include "sensirion_uart_hal.h"

static uint8_t communication_buffer[140] = {0};

int16_t sfc6xxx_close_valve() {
    int16_t local_error = 0;
    local_error = sfc6xxx_set_setpoint(0);
    return local_error;
}

int16_t sfc6xxx_set_setpoint(float setpoint) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x0, SFC6XXX_SHDLC_ADDR, 5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 1);
    sensirion_shdlc_add_float_to_frame(&frame, setpoint);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_get_setpoint(float* setpoint) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x0, SFC6XXX_SHDLC_ADDR, 1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 1);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *setpoint = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_read_measured_value(float* measured_value) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x8, SFC6XXX_SHDLC_ADDR, 1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 1);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *measured_value = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_read_averaged_measured_value(uint8_t measurements,
                                             float* averaged_measured_value) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x8, SFC6XXX_SHDLC_ADDR, 2);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 17);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, measurements);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(200 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *averaged_measured_value = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_set_setpoint_and_read_measured_value(float setpoint,
                                                     float* measured_value) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x3, SFC6XXX_SHDLC_ADDR, 5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 1);
    sensirion_shdlc_add_float_to_frame(&frame, setpoint);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *measured_value = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_set_user_controller_gain(float gain) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x22, SFC6XXX_SHDLC_ADDR,
                                5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 0);
    sensirion_shdlc_add_float_to_frame(&frame, gain);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_get_user_controller_gain(float* gain) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x22, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *gain = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_set_user_init_step(float init_step) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x22, SFC6XXX_SHDLC_ADDR,
                                5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 3);
    sensirion_shdlc_add_float_to_frame(&frame, init_step);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_get_user_init_step(float* init_step) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x22, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 3);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *init_step = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_measure_raw_flow(uint16_t* flow) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x30, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 2, &header);
    *flow = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_measure_raw_thermal_conductivity_with_closed_valve(
    uint16_t* thermal_conductivity) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x30, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 2);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(600 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 2, &header);
    *thermal_conductivity = sensirion_common_bytes_to_uint16_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_measure_temperature(float* temperature) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x30, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 16);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *temperature = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_get_number_of_calibrations(uint32_t* number_of_calibrations) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x40, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *number_of_calibrations =
        sensirion_common_bytes_to_uint32_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_get_calibration_validity(uint32_t index, bool* validity) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x40, SFC6XXX_SHDLC_ADDR,
                                5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 16);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, index);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 1, &header);
    *validity = (bool)buffer_ptr[0];
    return local_error;
}

int16_t sfc6xxx_get_calibration_gas_id(uint32_t index, uint32_t* gas_id) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x40, SFC6XXX_SHDLC_ADDR,
                                5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 18);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, index);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *gas_id = sensirion_common_bytes_to_uint32_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_get_calibration_gas_unit(uint32_t index, int8_t* prefix,
                                         uint8_t* unit, uint8_t* timebase) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x40, SFC6XXX_SHDLC_ADDR,
                                5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 19);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, index);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 3, &header);
    *prefix = (int8_t)buffer_ptr[0];
    *unit = (uint8_t)buffer_ptr[1];
    *timebase = (uint8_t)buffer_ptr[2];
    return local_error;
}

int16_t sfc6xxx_get_calibration_fullscale(uint32_t index, float* fullscale) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x40, SFC6XXX_SHDLC_ADDR,
                                5);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 20);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, index);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *fullscale = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_get_current_gas_id(uint32_t* gas_id) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x44, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 18);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *gas_id = sensirion_common_bytes_to_uint32_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_get_current_gas_unit(int8_t* prefix, uint8_t* unit,
                                     uint8_t* timebase) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x44, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 19);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 3, &header);
    *prefix = (int8_t)buffer_ptr[0];
    *unit = (uint8_t)buffer_ptr[1];
    *timebase = (uint8_t)buffer_ptr[2];
    return local_error;
}

int16_t sfc6xxx_get_current_fullscale(float* fullscale) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x44, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 20);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *fullscale = sensirion_common_bytes_to_float(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_set_calibration(uint32_t calibration_number) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x45, SFC6XXX_SHDLC_ADDR,
                                4);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, calibration_number);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_get_calibration(uint32_t* calibration_number) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x45, SFC6XXX_SHDLC_ADDR,
                                0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *calibration_number = sensirion_common_bytes_to_uint32_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_set_calibration_volatile(uint32_t calibration_number) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x46, SFC6XXX_SHDLC_ADDR,
                                4);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, calibration_number);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(20 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_set_slave_address(uint8_t slave_address) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x90, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, slave_address);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_get_slave_address(uint8_t* slave_address) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x90, SFC6XXX_SHDLC_ADDR,
                                0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 1, &header);
    *slave_address = (uint8_t)buffer_ptr[0];
    return local_error;
}

int16_t sfc6xxx_set_baudrate(uint32_t baudrate) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x91, SFC6XXX_SHDLC_ADDR,
                                4);
    sensirion_shdlc_add_uint32_t_to_frame(&frame, baudrate);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    return local_error;
}

int16_t sfc6xxx_get_baudrate(uint32_t* baudrate) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0x91, SFC6XXX_SHDLC_ADDR,
                                0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 4, &header);
    *baudrate = sensirion_common_bytes_to_uint32_t(&buffer_ptr[0]);
    return local_error;
}

int16_t sfc6xxx_get_product_type(int8_t* product_type,
                                 uint16_t product_type_size) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0xd0, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 64, &header);
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)product_type,
                                product_type_size);
    return local_error;
}

int16_t sfc6xxx_get_product_name(int8_t* product_name,
                                 uint16_t product_name_size) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0xd0, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 1);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 64, &header);
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)product_name,
                                product_name_size);
    return local_error;
}

int16_t sfc6xxx_get_article_code(int8_t* article_code,
                                 uint16_t article_code_size) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0xd0, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 2);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 64, &header);
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)article_code,
                                article_code_size);
    return local_error;
}

int16_t sfc6xxx_get_serial_number(int8_t* serial_number,
                                  uint16_t serial_number_size) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0xd0, SFC6XXX_SHDLC_ADDR,
                                1);
    sensirion_shdlc_add_uint8_t_to_frame(&frame, 3);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(50 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 64, &header);
    sensirion_common_copy_bytes(&buffer_ptr[0], (uint8_t*)serial_number,
                                serial_number_size);
    return local_error;
}

int16_t sfc6xxx_get_version(uint8_t* firmware_major, uint8_t* firmware_minor,
                            bool* firmware_debug, uint8_t* hardware_major,
                            uint8_t* hardware_minor, uint8_t* protocol_major,
                            uint8_t* protocol_minor) {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0xd1, SFC6XXX_SHDLC_ADDR,
                                0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(10 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 7, &header);
    *firmware_major = (uint8_t)buffer_ptr[0];
    *firmware_minor = (uint8_t)buffer_ptr[1];
    *firmware_debug = (bool)buffer_ptr[2];
    *hardware_major = (uint8_t)buffer_ptr[3];
    *hardware_minor = (uint8_t)buffer_ptr[4];
    *protocol_major = (uint8_t)buffer_ptr[5];
    *protocol_minor = (uint8_t)buffer_ptr[6];
    return local_error;
}

int16_t sfc6xxx_device_reset() {
    struct sensirion_shdlc_rx_header header;
    struct sensirion_shdlc_buffer frame;
    int16_t local_error = NO_ERROR;
    uint8_t* buffer_ptr = communication_buffer;
    sensirion_shdlc_begin_frame(&frame, buffer_ptr, 0xd3, SFC6XXX_SHDLC_ADDR,
                                0);
    sensirion_shdlc_finish_frame(&frame);
    local_error = sensirion_shdlc_tx_frame(&frame);
    if (local_error) {
        return local_error;
    }
    sensirion_uart_hal_sleep_usec(100 * 1000);
    local_error = sensirion_shdlc_rx_inplace(&frame, 0, &header);
    sensirion_uart_hal_sleep_usec(300 * 1000);
    return local_error;
}
